### ISSUE TITLE
Bom

### ISSUE THREAD

**Issue by claywd** [UltimateHackingKeyboard/uhk60v2-electronics#1]
Why not just use github actions to create the bom and release it as a package or something... I'm trying to generate it locally and getting all finds of errors and having not developed any of this myself... its a pain when I literally need the part number for a single smd.

**Comment by mondalaci** [comment]
I won't spend time setting up GitHub actions for this repo, but I can look into the relevant part if you explain what you need.

**Comment by claywd** [comment]
Okay. The SMD I need is the ESD Chip U5 on the right board with footprint id sc-74-tvs. There are lots of different diodes that match that footprint and form factor. Would like to get the same one used by the manufacturer.

One the other hand. If you want give me a little more info on how to get the tooling running well I can setup the github actions when I get a minute and PR it over for you.

**Comment by mondalaci** [comment]
This part is the ESD5V5U5ULCE6327HTSA1.

I'm sorry, but I don't want to allocate more time for this. Since the project's inception, no one has been interested in this, and we have much higher priorities. I'm closing this issue, but feel free to follow up.
